[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "kagglehub>=1.0.0",
    "polars>=1.38.1",
    "python-dotenv>=1.2.1",
    "spotdl>=4.4.3",
    "yt-dlp>=2026.2.21",
]
